### ISSUE TITLE
How to install on OpenHab 3.0.1 with Docker

### ISSUE THREAD

**Issue by erenoglu** [delid4ve/openhab-3.x-sonoff#2]
Hi, I've been pulling my hair off trying to install v3.0.0 on my docker installed OpenHab 3.0.1.
I downloaded the jar file org.openhab.binding.sonoff-3.0.0-SNAPSHOT_v2.0.jar  and placed it into the docker folder openhab_addons:
```
root@server:/srv/openhab/openhab_addons# ls -la
-rw-r--r-- 1 openhab openhab 150309 Mar  9 16:54 org.openhab.binding.sonoff-3.0.0-SNAPSHOT_v2.0.jar
-rw-r--r-- 1 openhab openhab     41 Mar  9 16:54 org.openhab.binding.sonoff-3.0.0-SNAPSHOT_v2.0.jar.sha1

```
In the bundles list, I can see it:
`217 │ Resolved │  80 │ 3.0.0.202102231457      │ openHAB Add-ons :: Bundles :: sonoff Binding`

But it does not show in features:list and when I go to web UI, click things on left, click "+" to add, it says "choose a binding" and sonoff is not listed there. I'm not sure where else I can add the "sonoff ewelink account" to get going. 

What could I be doing wrong?  I even tried to manually create a bundle directory in openhab_userdata next to some other bindings, but that also did not help.

**Comment by delid4ve** [comment]
there was a bug in the build system when this was compiled.  Ive just added a new version so please try this.
