### ISSUE TITLE
No channels appear

### ISSUE THREAD

**Issue by etairaz** [delid4ve/openhab-3.x-sonoff#4]
EDIT: Just my luck, I see that you are now updating everything, so I'm guessing my issue report isn't going to be very useful...
Where did the jars go?
**
Thanks for your hard work!
From OH3, I managed to connect to ewelink server, and all "things" seem to be online. However, openhab does not seem to be able to identify any channels on the things, hence items do not get updated, although it seems like behind the scenes the system does get updates:

> 2021-04-21 16:29:16.168 [DEBUG] [onoff.internal.helpers.MessageSystem] - Websocket received message: {"action":"update","deviceid":"a4b0002504","apikey":"67184dee-cb09-46b7-a7a5-xxx","userAgent":"device","d_seq":19878,"params":{"motion":1,"trigTime":"1619011733529"},"from":"device"}

Going through the settings screen, it seems like the motion detector channels are not recognized by the UI:
![image](https://user-images.githubusercontent.com/101089/115566676-22236700-a2c3-11eb-84d6-3f6caeeba5b3.png)

Finally, I realized that I'm using the wrong version probably (downloaded the latest jar, but I'm running OH3.0.1). I then tried it with the 3.0.1 version, but this one seems to not support the motion detector that I was testing. Autodiscovery comes back with sonoff:device instead of sonoff:2106

**Comment by delid4ve** [comment]
This is the latest version: https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_v2.4r2.jar

can you let me know with this please as I am using the zigbee motion and works ok. I’m assuming you ran discovery to create the cache too?

**Comment by etairaz** [comment]
Unfortunately the link leads to 404...
I did run discovery to create the cache. I'm using OH3.0.1, and tried both the 3.1 jar and 3.0.1 jars. 
3.1 leads to no channels appearing on the devices. 3.0.1 doesn't recognize the device type (so uid is sonoff:device, instead of sonoff:1226.
If you provide me with the latest version of the jar, I can certainly try again.

**Comment by delid4ve** [comment]
Right, the device isn’t currently supported, that’s why it has no channels. Can you send me the cache file generated for the device under userdata/sonoff and I’ll get it added.

**Comment by etairaz** [comment]
Attached is the content of the two cache files that were created, consolidated into a single file

[sonoff.txt](https://github.com/delid4ve/openhab-3.x-sonoff/files/6370246/sonoff.txt)

**Comment by delid4ve** [comment]
Uuid's are not 1226..
Zigbee bridge is 66
Motion sensor is 2026

Both are supported already.
Make sure you are using the latest jar in /openhab-Sonoff-compiled as I have both these devices on 3.0.1 and both are working perfectly
