### ISSUE TITLE
Sonoff Zigbee things 

### ISSUE THREAD

**Issue by TefiLaci** [delid4ve/openhab-3.x-sonoff#5]
I using OH3.0.2 and Sonoff v2.5r1.jar and I have problems with the Sonoff Zigbee wireless switch - SNZB-01 -. 
The sonoff binding auto discovered, but can't add. - Error during thing creation: Conflict -
Cache file: [cache_SNZB-01.txt](https://github.com/delid4ve/openhab-3.x-sonoff/files/6380119/cache_SNZB-01.txt)
Log: [log_SNZB-01.txt](https://github.com/delid4ve/openhab-3.x-sonoff/files/6380124/log_SNZB-01.txt)

Could you help me ?
Thanks in advance!

**Comment by delid4ve** [comment]
I'll try and get this added today, it's not yet implemented.

**Comment by delid4ve** [comment]
Let me know this works.  You'll definitely have to delete the thing and re-discover.  If that doesn't work then clear cache.
https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_2.5r3.jar

**Comment by TefiLaci** [comment]
Many thanks for you, 2.5r3 works fine without clearing the cache.

**Comment by delid4ve** [comment]
Good stuff
