### ISSUE TITLE
Sonoff Zigbee things

### ISSUE THREAD

**Issue by TefiLaci** [delid4ve/openhab-3.x-sonoff#7]
I using OH3.0.2 with Sonoff v2.5r3.jar and I have problems with the Sonoff Zigbee door/window open switch - SNZB-04 -.
The sonoff binding auto discovered, but can't add. - Error during thing creation: Conflict 
Cache file: [cache_SNZB-04.txt](https://github.com/delid4ve/openhab-3.x-sonoff/files/6541860/cache_SNZB-04.txt)
log: [log_SNZB-04.txt](https://github.com/delid4ve/openhab-3.x-sonoff/files/6541863/log_SNZB-04.txt)

Thanks for your help in advance!

**Comment by delid4ve** [comment]
That’s because it wasn’t integrated at that point, you need https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-3.0.3-SNAPSHOT_2.5r5.jar

**Comment by TefiLaci** [comment]
That's works, thank you for your work!
